### ISSUE TITLE
TC2 Global_Variables are not recognized

### ISSUE THREAD

**Issue by NilsTC** [dkleber89/ioBroker.beckhoff#3]
TC2 needs a "." at the beginning.

**Comment by dkleber89** [comment]
Are u firm with node, npm and Beckhoff?

Is it possible for u, that u use this Project: https://github.com/dkleber89/beckhoffTest on a Testsystem in combination with a TwinCat2 PLC and give me back the Console Log Output?

I need to know how variables exactly looks like.

Im not able to run a TwinCat2 Runtime on a x64 System and i have no PLC or x86 System here.

**Comment by NilsTC** [comment]
Not really....
I just tried it in VS to start.
It also comes out a debugg file.
I can not find useful information in it. Probably I'm doing something wrong.

How should I proceed?

**Comment by dkleber89** [comment]
I have the needed Information yet ... I see that i need to change many things for TC2
