### ISSUE TITLE
Is it currently possible to synchronize more than one variable

### ISSUE THREAD

**Issue by PLCHome** [dkleber89/ioBroker.beckhoff#33]
I am trying to replace my Node Red with ioBroker. Hence the question, is it currently possible to synchronize more than one variable between iobroker and Twincat?

I only found the input for a variable.

**Comment by PLCHome** [comment]
?

**Comment by dkleber89** [comment]
Oh sorry for the late response ... i don't get a notification from Github ... Yes for sure its possible ... The input is not for a Variable ... in TwinCat 3 it's for a Global Variable Table and in TwinCat 2 its for a global Struct

**Comment by dkleber89** [comment]
The Adapter syncronises all Variables automatic in the ioBroker (Complete Tree) but only when all Variables inside are supported ... See readme

**Comment by PLCHome** [comment]
So only one variable that contains a structure can be registered.
.VarStruct1
.VarStruct2
it does not work.

**Comment by dkleber89** [comment]
Yes that is true

**Comment by PLCHome** [comment]
What do you think if I convert the configuration to tab and install a tab in which you can specify more than one variable table?
The currently maintained variable could be transferred to the first line. I would implement it and make a merge request.

It could look like this:

![image](https://user-images.githubusercontent.com/29116097/87766352-53917280-c819-11ea-803a-90849c6aecf9.png)

**Comment by dkleber89** [comment]
That's a good idea ... It's would be a good feature and a good improvement for the Adapter to use more than one Struct/V-Table

**Comment by dkleber89** [comment]
I would be happy when u implement this ... Looking forward for your merge request

**Comment by Timmes123** [comment]
Hi :-) i work with your adapter and for me it would be great, if the adapter get this update.
I have a lot variables i have to read from existing PLCs, and i dont want to change software in every PLC and integrate a interface vartable. 
it would be great, if i can define the needed variables in iobroker, without touching the plc

**Comment by dkleber89** [comment]
@PLCHome ... Are u working on that? Or is this issue obsolete?

**Comment by dkleber89** [comment]
Close because stale
