### ISSUE TITLE
Übergabe der Rollen für Channel und State aus der Beckhoff-SPS

### ISSUE THREAD

**Issue by DaHi35** [dkleber89/ioBroker.beckhoff#42]
Hi,

ist es möglich die an den ioBroker übergebenen Strukturen und deren Inhalt schon in der SPS eine *Rolle* zuzuweisen? Mein erster Gedanke war es, einen Kommentar hinter dem Strukturnamen und der Variable zu schreiben in dem die passende *Rolle* steht und diesen Kommentar dann im ioBroker/Adapter zu verarbeiten und entsprechend einzufügen. Hintergrund ist die automatische Erstellung von Visualisierungen, beipielsweise in *iQontrol*, und die automatische Verknüpfung der passenden Variablen an den Baustein in der Visualisierung. 

Eine Auflistung mit sämtlichen Rollen für die Channel findet sich [hier](https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/objectsschema.md).
Eine Auflistung mit sämtlichen Rollen für die Variablen findet sich [hier](https://github.com/ioBroker/ioBroker/blob/master/doc/STATE_ROLES.md).

**Screenshots**

Ich habe hier mal zwei Leuchten angelegt und die erste von Hand angepasst. Wenn man die Struktur passend kommentieren würde und die *Rollen* automatisch übergeben würden, würde das einige Arbeit ersparen. In die Zelle *Rolle* des *Channels* müsste laut der oben verlinkten Auflistung die *Rolle Light* eingefügt werden, allerdings wird das nicht übernommen, egal wie ich die Eingabe bestätige - bei anderen Adaptern klappt's. Muss das im Beckhoff-Adapter noch freigegeben werden?

![Screenshot ioBroker](https://user-images.githubusercontent.com/82456306/114828117-cf7d1300-9dc9-11eb-8061-3a85fb6439fe.PNG)

Wenn Du Rückfragen hast, stehe ich gerne zur Verfügung.

Gruß,
DaHi35

**Comment by dkleber89** [comment]
Hallo @DaHi35,

ich habe grad nicht im Kopf ob ich die Kommentare aus der SPS über ADS überhaupt mitbekomme wenn ich die Symbole anfordere. 

Von meiner Seite muss ich diesem Feature aber zumindest derzeit eine Absage erteilen. Ich habe überhaupt keine Zeit mir das anzuschauen. Und für meine Anwendungen benötige ich das nicht. Ich bin auf jeden Fall offen für das Feature falls es jemanden gibt der sich dem Annehmen will und sehe mir gerne einen PullRequest dazu an.
