### ISSUE TITLE
Support of TOD and DT Variables

### ISSUE THREAD

**Issue by NilsTC** [dkleber89/ioBroker.beckhoff#46]
it would be nice if the data types DT and TOD were also supported. I saw that you are now in the node-ads-api.

**Comment by dkleber89** [comment]
Müsste ich mir anschauen wie einfach das funktioniert ... Wäre sicher super wenn das der Adapter auch könnte ... Aus Zeitgründen würde ich mich auch sehr über PR´s freuen ;-)

**Comment by PLCHome** [comment]
Ist im pull request

**Comment by dkleber89** [comment]
Danke @PLCHome für den PR -> Habe das Testenvironment gefixt und deine Änderungen gemerged. Version 1.5.1 Hat jetzt die neuen Datentypen
