### ISSUE TITLE
ACK status von ADS Com

### ISSUE THREAD

**Issue by hartmannf** [dkleber89/ioBroker.beckhoff#60]
Hallo 

In Verbindung mit MQTT und  weiterreichen von Daten an Openhab und zurück ist die Frage aufgetaucht ob es eine Möglichkeit gibt den Status von ACK abzufragen oder diesen zu manipulieren ? 

Weiterreichen von daten mit MQTT Broker und einen externen Broker funktioniert, jedoch von MQTT Cloud nicht wieder in den Beckhoffadapter variablen.

**Comment by dkleber89** [comment]
Hallo,

ich denke du meinst den ACK Status der jeweiligen States im ioBroker?

**Abfragen** ist kein Problem. Wenn du den State liest kommt der ACK Status in den Metadaten mit.

Wenn dieser **Manipuliert** wird kann es zu fehlerhaftem Verhalten des Adapters kommen. 

Über den ACK Status wird vom Adapter festgestellt ob eine Variable zur SPS geschrieben werden muss. Soll heißen, immer wenn ein State vorhanden ist der ACK auf "false" hat wird dieser automatisch zur SPS geschrieben und durch den Sync prozess auf ACK  true gesetzt. Weiters wird der State bei einer Veränderung in der SPS neu beschrieben und dementsprechend ACK auf "true" gesetzt. 

Dies ist im ioBroker eine Grundsätzliche Mechanik die von jedem Adapter in der oder ähnlicher Form verwendet wird.
