### ISSUE TITLE
 Each element of the structure is registered individually

### ISSUE THREAD

**Issue by PLCHome** [dkleber89/ioBroker.beckhoff#66]
I noticed that when I load a structure, each element is registered individually in the PLC. 
Beckhoff says that you should not register more than 500 notifications.
https://infosys.beckhoff.com/english.php?content=../content/1033/tc3_adsnetref/7312578699.html&id=
Currently, 500 notifications are registered for a structure with 500 elements

You can reduce the amount by registering the whole type and not each element individually. 
But that will be a major change.

**Comment by dkleber89** [comment]
Hopefully this get addressed with the Adapter rewrite ... But there ist no timeline
